version: '2'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: nrdbv2

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ../netrunner-data/:/netrunner-data
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres:
